"""
SVG 字体转 TTF 字体转换器
使用 fontforge 库将 SVG 字体文件转换为 TTF 文件
"""

def convert_svg_to_ttf(svg_path, ttf_path, font_name):
    """
    将 SVG 字体转换为 TTF 字体
    
    Args:
        svg_path: SVG 字体文件路径
        ttf_path: 输出的 TTF 文件路径
        font_name: 字体名称
    
    Returns:
        str: "success" 或错误消息
    """
    try:
        import fontforge
        import os
        
        # 检查 SVG 文件是否存在
        if not os.path.exists(svg_path):
            return f"SVG file not found: {svg_path}"
        
        print(f"Opening SVG font: {svg_path}")
        
        # 打开 SVG 字体文件
        font = fontforge.open(svg_path)
        
        # 设置字体属性
        font.fontname = font_name.replace(" ", "")
        font.familyname = font_name
        font.fullname = font_name
        font.weight = "Regular"
        font.copyright = "Generated by FontMaster"
        
        # 设置字体度量
        font.em = 1000
        font.ascent = 800
        font.descent = 200
        
        print(f"Font properties set: {font.fontname}")
        print(f"Generating TTF: {ttf_path}")
        
        # 生成 TTF 文件
        font.generate(ttf_path, flags=("opentype",))
        
        print("TTF generation completed")
        
        # 关闭字体
        font.close()
        
        # 验证生成的文件
        if os.path.exists(ttf_path):
            file_size = os.path.getsize(ttf_path)
            print(f"TTF file created: {file_size} bytes")
            return "success"
        else:
            return "TTF file was not created"
        
    except ImportError as e:
        error_msg = f"FontForge not available: {str(e)}"
        print(error_msg)
        return error_msg
    except Exception as e:
        error_msg = f"Error converting SVG to TTF: {str(e)}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        return error_msg


# 用于测试的主函数
if __name__ == "__main__":
    import sys
    
    if len(sys.argv) != 4:
        print("Usage: python svg_to_ttf.py <svg_path> <ttf_path> <font_name>")
        sys.exit(1)
    
    svg_path = sys.argv[1]
    ttf_path = sys.argv[2]
    font_name = sys.argv[3]
    
    result = convert_svg_to_ttf(svg_path, ttf_path, font_name)
    if result == "success":
        print("Conversion successful!")
        sys.exit(0)
    else:
        print(f"Conversion failed: {result}")
        sys.exit(1)

